version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin            # Логин для root-доступа
      MINIO_ROOT_PASSWORD: password123  # Пароль
    volumes:
      - ./minio_data:/data              # Папка для хранения данных
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Веб-консоль
    restart: unless-stopped

  mc:
    image: minio/mc
    container_name: mc
    entrypoint: >
      /bin/sh -c "
      sleep 5;  # Ждем запуска MinIO
      mc alias set local http://minio:9000 admin password123;
      mc admin info local;
      tail -f /dev/null  # Чтобы контейнер не завершался
      "
    depends_on:
      - minio